apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: containerization_hw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: containerization_hw
  template:
    metadata:
      labels:
        app: containerization_hw
    spec:
      containers:
        - name: server
          image: server
          ports:
            - containerPort: 5000
          imagePullPolicy: Never


---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: containerization_hw
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: containerization_hw